proxy:
  image: pumgrana-proxy:latest
  restart: always
  environment:
    CONF_FILE: pumgrana.conf
  ports:
    - "8080:80"
  links:
    - pum-api
    - dashboard

dashboard:
  image: pumgrana-dashboard:latest
  restart: always

pum-api:
  image: pumgrana-pum-api:latest
  restart: always
  ports:
    - "3000:3000"
  links:
    - elasticsearch
    - postgres

elasticsearch:
  image: pumgrana-elasticsearch:latest
  restart: always
  environment:
    ES_HEAP_SIZE: 2g
  volumes:
    - /srv/data/elasticsearch/test:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
  command: "./bin/elasticsearch -Des.nodes.discovery=false"

postgres:
  image: pumgrana-postgres:latest
  restart: always
  volumes:
    - /srv/data/pgsql/test:/var/lib/postgresql/data
